### ISSUE TITLE
Old migration name affecting new view name

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [scenic-views/scenic#394] opened 2023-07-04 02:17 UTC
Hi,
It seems like scenic depends on the file name of migrations to detect if a certain view was already created.

In my case I have a migration from 2015 (!) that's called `2015xxxx_create_membership_cards.rb` and today when I wrote `rails g scenic:view membership_cards --replace` it created the "view file" (the SQL statement), but no migration.
The table "membership_cards" has been renamed in a different migration, so "membership_cards" is definitely available as view name.

One solution could be to "prefix" all the file names with _view, such as `2023xxxx_create_view_VIEWNAME.rb` instead of just `2023xxxx_create_VIEWNAME.rb`

I worked around it by doing:

```bash
rails g scenic:view public_membership_cards --replace
```

Then I renamed the file from `public_membership_cards_v01.sql` to `membership_cards_v01.sql` and altered the migration to have `create_view(:membership_cards)` inside.

**Comment by derekprior** [comment] 2023-09-29 16:04
> It seems like scenic depends on the file name of migrations to detect if a certain view was already created.

This is not correct. AFAIK, Scenic has no code in place to scan migration file names, although we _do_ scan the view (SQL) files to determine the next version number to use.

I'm not sure what's happening here. Could you please provide:

1. The ruby, rails, and scenic version you are running
2. The command you are running, complete with _all_ output from that command
3. The output of `git status` after running the command (with `status` being clean before you run the generator)

**Comment by Fire-Dragon-DoL** [comment] 2023-12-02 19:30
I finally got to this, sorry it took so long. I created a repository to the point of replicating the issue:

https://github.com/Fire-Dragon-DoL/scenic_exp

The README includes a step-by-step replication of the issue.

Now to answer your questions (specific to this experiment repo):

### The ruby, rails, and scenic version you are running

Rails 7.1, Ruby 3.2.2, Scenic 1.7.0

### The command you are running, complete with all output from that command

```bash
rails generate scenic:view recipes
```
The output is:

```
$ rails generate scenic:view recipes
      create  db/views/recipes_v01.sql
    conflict  db/migrate/20231202192024_create_recipes.rb
Another migration is already named create_recipes: /home/francesco/Projects/Experiments/scenic_exp/db/migrate/20231202191127_create_recipes.rb. Use --force to replace this migration or --skip to ignore conflicted file.
```

### The output of git status after running the command (with status being clean before you run the generator)

Status is clean, after running the command I get:

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        db/views/

nothing added to commit but untracked files present (use "git add" to track)
```

And if I do git add on `db/views` I see the following

```bash
git add db/views
git status
```

```
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   db/views/recipes_v01.sql

```

**Comment by derekprior** [comment] 2023-12-03 02:53
I don't understand why `20231202192024_create_recipes.rb` would claim it already exists. The point of the `timestamp` in the filename is to avoid that. What's in that file?

**Comment by derekprior** [comment] 2024-01-17 18:25
We've not had any other reports of this issue, so I'm going to close this. If you have a reproducible base case and push a sample app up somewhere, I'm happy to take a look.

**Comment by Fire-Dragon-DoL** [comment] 2024-01-17 18:55
> We've not had any other reports of this issue, so I'm going to close this. If you have a reproducible base case and push a sample app up somewhere, I'm happy to take a look.

Was the repository not sufficient? Downloading the repository and following the README would trigger immediately the error, so it can be observed: https://github.com/Fire-Dragon-DoL/scenic_exp

**Comment by derekprior** [comment] 2024-01-17 21:55
Ah, sorry, I had missed that you supplied an app already. I just played around with it and found it really curious that if you pass `--force` with the generator, the command succeeds but deletes a file that shouldn't have conflicted anyway...

```
❯ rails generate scenic:view recipes --force

      create  db/views
      create  db/views/recipes_v01.sql
      remove  db/migrate/20231202191127_create_recipes.rb
      create  db/migrate/20240117215356_create_recipes.rb
```

**Comment by derekprior** [comment] 2024-01-17 21:58
This does not appear to be an issue with Scenic as I can remove scenic and still get the same error trying to use the model generator (which scenic relies on under the hood here too):

```
❯ rails generate model recipe 
      invoke  active_record
    conflict    db/migrate/20240117215744_create_recipes.rb
Another migration is already named create_recipes: /Users/derek/src/Fire-Dragon-DoL/scenic_exp/db/migrate/20231202191127_create_recipes.rb. Use --force to replace this migration or --skip to ignore conflicted file.
```

Looks like a rails bug. I will spend a few minutes seeing if I can pinpoint where.

**Comment by Fire-Dragon-DoL** [comment] 2024-01-17 22:04
> This does not appear to be an issue with Scenic as I can remove scenic and still get the same error trying to use the model generator (which scenic relies on under the hood here too):
> 
> ```
> ❯ rails generate model recipe 
>       invoke  active_record
>     conflict    db/migrate/20240117215744_create_recipes.rb
> Another migration is already named create_recipes: /Users/derek/src/Fire-Dragon-DoL/scenic_exp/db/migrate/20231202191127_create_recipes.rb. Use --force to replace this migration or --skip to ignore conflicted file.
> ```
> 
> Looks like a rails bug. I will spend a few minutes seeing if I can pinpoint where.

Thank you. Yeah I suspected that was a Rails problem

**Comment by derekprior** [comment] 2024-01-17 22:07
I think this is pretty much how it always worked... or has for quite some time. The class name inside the migration is derived from the non-timestamped file name (or vice versa, but it doesn't matter) and they want to avoid duplicate class names. I believe this is by design and in any event is not a scenic issue.

In your particular case, I would suggest manually creating a migration named `recreate_recipes` or something like that.

**Closed by derekprior** 2024-01-17 22:07 UTC
