### ISSUE TITLE
Views with regexp and postgres

### ISSUE THREAD

**Issue by lucasmpb** [scenic-views/scenic#242] opened 2018-05-26 13:51 UTC
I think there is an issue, when views with regular expressions are not correctly been including on schema.rb file.
As an example, if we have a view like
```
SELECT * FROM table WHERE name::text ~ 'qe(\d+)'::text
```
On the schema.rb file is added as
```
SELECT * FROM table WHERE name::text ~ 'qe(d+)'::text
```
(note the missing `\`) breaking the regexp

**Comment by derekprior** [comment] 2019-02-03 00:47
I looked into this, and the issue seemingly exists either in PG or in `pg_get_viewdef` itself. I created a test case for this and did some debugging. We run the following query:

```SQL
            SELECT
              c.relname as viewname,
              pg_get_viewdef(c.oid) AS definition,
              c.relkind AS kind,
              n.nspname AS namespace
            FROM pg_class c
              LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE
              c.relkind IN ('m', 'v')
              AND c.relname NOT IN (SELECT extname FROM pg_extension)
              AND n.nspname = ANY (current_schemas(false))
            ORDER BY c.oid
          SQL
```

When we execute this query we get back a `PG::Result`. This PG::Result strips the `\`.

I don't think there's anything we can do here. I'm going to close this, but if you think I'm mistaken, please ping the issue again.

**Closed by derekprior** 2019-02-03 00:47 UTC

**Comment by derekprior** [comment] 2019-02-03 00:50
You can try it out for yourself debugging this branch, if you'd like: 
https://github.com/scenic-views/scenic/compare/dp-regex-views?expand=1

**Comment by bensheldon** [comment] 2020-06-02 00:01
I'm having this problem with regexp, but I'm seeing different behavior depending on whether the views are being created as part of a migration, or as part of `schema:load`. 

- Created as part of migration: the resulting definition in `pg_mat_views` correctly has a backslash. Also, running `pg_get_viewdef('my_view')` correctly returns a definition with a backslash too.
- Created as part of `bin/rails db:schema:load` (or `db:reset`): the resulting definition in pg_mat_views` incorrectly does not have a backslash, nor does `pg_get_viewdef('my_view')`

I think the problem is that the backslash requires a double-backslash when it's being outputted into the `schema.rb` file in the HEREDOC. 

I'll look further at the debugging branch.

**Comment by calebthompson** [comment] 2020-06-02 15:07
> I'm seeing different behavior depending on whether the views are being created as part of a migration, or as part of schema:load.

That makes sense - migrations run the view definition from the source, which will have the backslash. schema:load will have the _dumped_ view definition, which has the result @derekprior mentioned of PG::Result dropping the `\`.

**Comment by bensheldon** [comment] 2020-06-02 15:31
After further investigation I'm confident the problem is within Scenic, not Postgres. Scenic is losing the backlash when it writes out the schema. 

I opened up a PR in #303 to escape the backslash.
