### ISSUE TITLE
Not support WITH clause

### ISSUE THREAD

**Issue by n5ken** [scenic-views/scenic#310] opened 2020-11-28 14:48 UTC
I am trying to create a view with `WITH` clause but failed, is there any workaround to do this? 

Example:
```sql
-- source: https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates
CREATE VIEW conditions_summary_hourly
WITH (timescaledb.continuous) AS
SELECT device,
       time_bucket(INTERVAL '1 hour', time) AS bucket,
       AVG(temperature),
       MAX(temperature),
       MIN(temperature)
FROM conditions
GROUP BY device, bucket;
```

**Comment by derekprior** [comment] 2020-11-28 21:02
What are you putting in the scenic generated sql file and what error do you get when you migrate?

**Comment by n5ken** [comment] 2020-11-30 15:57
Here are steps to reproduce:

Create view files
```
% rails generate scenic:view conditions_summary_hourly
      create  db/views
      create  db/views/conditions_summary_hourlies_v01.sql
      create  db/migrate/20201127145457_create_conditions_summary_hourlies_v01.rb
% rake db:migrate
== 20201127145457 CreateConditionsSummaryHourlies: migrating ======================
-- create_view(:conditions_summary_hourlies)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
...
Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 1: CREATE VIEW "conditions_summary_hourlies" AS WITH (timescaledb.c...
```

Here is what sql file look like:
```ruby
WITH (timescaledb.continuous) AS
SELECT device,
       time_bucket(INTERVAL '1 hour', time) AS bucket,
       AVG(temperature),
       MAX(temperature),
       MIN(temperature)
FROM conditions
GROUP BY device, bucket;
``` 

From source code (postgres adapter), I think `WITH` clause is not support:
https://github.com/scenic-views/scenic/blob/048e08057e0bd76a700e7759344000cdc4e78235/lib/scenic/adapters/postgres.rb
```
      # Creates a view in the database.
      #
      # This is typically called in a migration via {Statements#create_view}.
      #
      # @param name The name of the view to create
      # @param sql_definition The SQL schema for the view.
      #
      # @return [void]
      def create_view(name, sql_definition)
        execute "CREATE VIEW #{quote_table_name(name)} AS #{sql_definition};"
      end
```

**Comment by derekprior** [comment] 2020-12-01 02:52
You should be able to create a view that uses a common table expression (CTE). I'm not a CTE expert, but something like this in your sql file would work:

```
WITH foo as (SELECT a,b FROM x)
SELECT foo.a, posts.b
FROM posts
INNER JOIN foo ON foo.b = posts.b
```

In your example, I don't think you'd want parens around the name you're giving to the CTE (and I'm not sure you can have a dot in it either), but instead would want it around the definition. And then you'd have to use that definition in the view following the CTE.

I can't say for sure what you want to do should work because I haven't tried it but I think it should if you get the SQL right.

**Comment by MadBomber** [comment] 2020-12-02 00:09
I just did a test (PostgreSQL v12.4) with a materialized view that relies heavily on common table expression (CTE) without difficulty.

**Comment by n5ken** [comment] 2020-12-02 03:03
> I just did a test (PostgreSQL v12.4) with a materialized view that relies heavily on common table expression (CTE) without difficulty.

hi @MadBomber, could you share your test case? according to my test case and Scenic postgres adapter, the actual sql will look like:

```sql
CREATE VIEW "conditions_summary_hourlies" AS
WITH (timescaledb.continuous) AS
SELECT device,
       time_bucket(INTERVAL '1 hour', time) AS bucket,
       AVG(temperature),
       MAX(temperature),
       MIN(temperature)
FROM conditions
GROUP BY device, bucket;
```

and will return:

```
LINE 1: CREATE VIEW "conditions_summary_hourlies" AS WITH (timescaledb.c...
```

**Comment by derekprior** [comment] 2020-12-02 03:05
@n5ken have you tried running that SQL directly in postgres?

**Comment by n5ken** [comment] 2020-12-02 07:23
> @n5ken have you tried running that SQL directly in postgres?

Yes, and it failed to run because there is an additional `AS` before `WITH`

Refer to synopsis in document: https://www.postgresql.org/docs/12/sql-createview.html, WITH clause allow me to specifies optional parameters for a view.

```
CREATE [ OR REPLACE ] [ TEMP | TEMPORARY ] [ RECURSIVE ] VIEW name [ ( column_name [, ...] ) ]
    [ WITH ( view_option_name [= view_option_value] [, ... ] ) ]
    AS query
    [ WITH [ CASCADED | LOCAL ] CHECK OPTION ]
```

And according to the create_view method, it seems there is no way to put `WITH` before `AS`

```ruby
# https://github.com/scenic-views/scenic/blob/048e08057e0bd76a700e7759344000cdc4e78235/lib/scenic/adapters/postgres.rb
def create_view(name, sql_definition)
  execute "CREATE VIEW #{quote_table_name(name)} AS #{sql_definition};"
end
```

And I think what it should look like:

```
def create_view(name, sql_definition, with_definition = '')
  execute "CREATE VIEW #{quote_table_name(name)} #{with_definition} AS #{sql_definition};"
end
```

The reason that I need to create view with view option: To create a view and enable continue aggregation 
https://docs.timescale.com/latest/api#continuous_aggregate-create_view-with-required

**Comment by amaierhofer** [comment] 2020-12-02 08:01
We are facing the exact same issue when combining scenic with timescale db caggs. I have created a fork at https://github.com/amaierhofer/scenic which modify the `create_view`, `update_view` and `drop_view` methods to take the required additional arguments. 

With those changes we are able to use caggs in migrations like this

```
class CreateMeasurements5Mins < ActiveRecord::Migration[6.0]
  def change
    create_view :measurements_5_mins, with: <<~SQL
      timescaledb.continuous,
      timescaledb.materialized_only = true,
      timescaledb.refresh_lag = '30 minutes',
      timescaledb.refresh_interval = '10 minutes'
    SQL
  end
end
```

Forward migrations work fine, not 100% sure about backwards migrations.

Also when dumping the schema, the view might reference chunks of the hypertable, which are not included in the schema dump. I believe this is unrelated to scenic but still a bummer. We currently work around this by running migrations instead of loading the schema when running tests.

 @n5ken let me know if the fork works for you and maybe we can work on this together to get this supported officially. What do you think @derekprior. I believe this also somewhat relates to https://github.com/scenic-views/scenic/issues/301

**Comment by n5ken** [comment] 2020-12-02 09:08
Thanks @amaierhofer! it looks so cool, I will try you fork soon.
I also encountered the same problem migrating tenant tables from schema.rb, and I guess using sql dump would help (not sure).
https://edgeguides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you

**Comment by alex-klepa** [comment] 2021-01-06 01:58
@derekprior why it's closed, the issue is not resolved?

@amaierhofer Can you submit PR?

**Comment by amaierhofer** [comment] 2021-02-17 14:00
@derekprior Is there any chance we could get something like this merged into scenic? What would be the implications? The change in the PR is trivial. Other people could benefit as well and have also indicated their willingness to work on this, see #301.

**Comment by derekprior** [comment] 2021-02-17 18:20
It's closed because I made a mistake in my original assessment. It happens from time to time. I don't think we're likely to take the PR as is from @amaierhofer because we want the SQL to live inside SQL files, not your migration.

If someone wanted to update Scenic to eloquently detect when the SQL files uses `with` and then perform the right SQL statement for that case, I think I'd be open to that. But honestly, I haven't put a lot of thought into it.

**Comment by MadBomber** [comment] 2021-02-17 23:23
Sorry; just saw the request for the test case I did back in december.  Short answer: No.  Long answer application is in healthcare industry where even some database schemas are consider too sensitive.

This seems like a problem that is specific to timescaledb which I do not use.

**Comment by derekprior** [comment] 2021-12-17 22:07
I've played with this some and couldn't come up with a solution I liked (tried, for example, frontmatter in the SQL file). That's not to say one doesn't exist, just that I didn't hit on it very easily. There are workarounds available: you can include nested queries rather than use CTEs or you could create the CTEs as separate, referenceable views. This should not be a blocker for anyone.

I'm going to close this as something we just don't currently support. If there's any interest in writing up a patch to support it, I encourage you to reach out first via our [new discussions forum](https://github.com/scenic-views/scenic/discussions) to see if the general shape of the solution would be agreeable before embarking.

**Closed by derekprior** 2021-12-17 22:07 UTC
Labels: schema statements

**Comment by jonatas** [comment] 2022-08-11 19:30
Hi folks, I know it's already closed, but if anyone still looking for this integration, I'm the creator of the [timescaledb gem](https://github.com/jonatas/timescaledb/) and @deepj implemented the Timescaledb extension for scenic allowing to use of the `with` clause [here](https://github.com/jonatas/timescaledb/blob/a366685305e0dcc30daecaa50ce7e438bcd80cbb/lib/timescaledb/scenic/extension.rb#L17).

**Comment by derekprior** [comment] 2022-08-12 15:40
The trouble with that solution is that it means rollbacks are dependent on you looking up the old `with` clause and making sure you put it in the migration.

The two ideas I have for avoiding this are:

1. Add some intelligence to the the SQL file processing so it extracts the `with` clause and uses the right syntax.
2. Look for a second versioned file for the `with` clause (e.g. `searches_v01.sql` would look for `searches_v01_with.sql` or something like that.

I'm more partial to the first option, but I just don't know that we could do it well.

**Comment by jonatas** [comment] 2022-08-15 13:19
Thanks for the input! I haven't used scenic in production until now, and I'll keep an eye if someone cross the need of rolling back, probably we can adopt one of the solutions that you suggested!
